# Generated by Django 5.2.6 on 2026-03-09 08:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafia_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('group_name', models.CharField(max_length=255)),
                ('gorup_link', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
