



uz_texts ={
    "ROLES_CHOICES" : [
    ("peace", "👨🏼 Tinch axoli"),
    ('nogiron',"👨🏻‍🦼‍➡️ Nogiron"),
    ('suid',"🤦🏻 Suidsid"),
    ("doc", "👨🏼‍⚕️ Shifokor"),
    ("daydi", "🧙🏼‍♂️ Daydi"),
    ("com", "🕵🏻‍♂️ Komissar katani"),
    ("kam", "💣 Kamikaze"),
    ("lover", "💃🏻 Mashuqa"),
    ("mafia", "🤵🏼 Mafia"),
    ("don", "🤵🏻 Don"),
    ("adv", "👨🏻‍💻 Advokat"),
    ("back_main", "⬅️ Orqaga"),
],
    "WINNER_LABEL" : {
    "peace": "👨🏼  Tinch axoli",
    "mafia": "🤵🏻 Mafialar",
},
    
"DESCRIPTIONS" : {
    "peace": "🧑🏻 Tinch aholi. Sizning vazifangiz — mafiani topish va kunduzgi ovoz berishda ularni osishga yordam berish.",
    "nogiron":"👨🏻‍🦼‍➡️ Nogiron Siz faqat aholi tarafsiz ovoz berish jarayonida mafiaga ovoz berib osasiz",
    "don": "🤵🏻 Don. Mafialar sardori. Har kecha qurbon tanlaysiz va butun mafia sizning qaroringizga bo'ysunadi.",
    "mafia": "🤵🏼 Mafia. Don bilan birga ishlaysiz, kechalari qurbon tanlaysiz. Don o'lsa uning o'rnini egallashingiz mumkin.",
    "com": "🕵🏻 Komissar. Har kecha o'yinchini tekshiradi, shubhali bo'lsa otishi ham mumkin. Tinch aholi himoyachisi.",
    "doc": "🧑🏻‍⚕️ Doktor. Har kecha bitta o'yinchini o'limdan saqlab qolishi mumkin. Tinch aholi umidi.",
    "lover": "💃🏻 Mashuqa. Tanlagan o'yinchini bir kechaga blok qiladi, u hech qanday harakat qila olmaydi.",
    "adv": "👨🏻‍💼 Advokat. Mafialar tarafdori. Tanlagan mafiani Komissar ko'ziga tinch aholi qilib ko'rsatadi.",
    "suid": "🤦🏻 Suidsid. Agar sizni kunduz osishsa, o'yin natijasidan qat’i nazar, darhol g'alaba qilasiz.",
    "daydi": "🧙🏻 Daydi. Kechasi bir uyga borib u yerda sodir bo'lgan voqealarning guvohi bo'lishi mumkin.",
    "kam": "💣 Kamikaze. Agar sizni osishsa, xohlagan bitta o'yinchini o'zingiz bilan olib ketishingiz mumkin.",
},


"ACTIONS" : {
    # Mafia
    "don_kill": "🤵🏻 Mafia keyingi qurboni uchun ovoz berish o'tkazyapti: ",
    "mafia_vote": "🤵🏻 Bugun kechasi kimni o'limiga ovoz berasiz?",
    "adv_mask": "👨🏻‍💻 Qaysi mafiya a'zosini yashiramiz?",
    
    # Peace
    "doc_heal": "👨🏼‍⚕️ Bugun tunda kimni davolaymiz?",
    "com_deside":" 🕵🏻‍♂️ Bugun kechasi nima qilmoqchisiz?",
    "com_check": "🔍 Kimni tekshiramiz?",
    "com_shoot": "🔫 Kimni otamiz?",
    "daydi_watch": "🧙🏼‍♂️ Bugun kechasi kimning uyiga shisha olish uchun borasiz?",
    "lover_block": "💃🏻 Bugun kechani kim bilan o'tkazmoqchisiz?",
   
    "kamikaze_blow": "💣 Kimni portlatamiz?",
    
  

},
        "punish_afk":"Tunda {role_label} <a href='tg://user?id={pid}'>{name}</a> vahshiylarcha o‘ldirildi...\nU o‘lim oldidan shunday so‘z qoldirdi:\n'Men o‘yin paytida boshqa uxlamayma-a-a-a-a-a-an!'",
        "reg_started": "Ro'yxatdan o'tish boshlandi",
        "reg_list": "Ro'yxatdan o'tganlar:",
        "total": "Jami {count}ta odam",
        "no_players": "Hali hech kim ro'yxatdan o'tmadi",
        "bot_no_rights": "⚠️ Botga yetarli admin huquqlari berilmagan!\nSalom! Men Mafia o'yinini rasmiy botiman.\n\nQuyidagi ruxsatlar kerak:\n",
        "bot_no_rights_add":"☑️ Admin qilish\n☑️ Xabarlarni o‘chirish\n☑️ A’zolarni cheklash\n☑️ Xabarlarni qadash\n",
        "bot_no_rights_delete":"☑️ Xabarlarni o‘chirish\n",
        "bot_no_rights_restrict":"☑️ A’zolarni cheklash\n",
        "bot_no_rights_pin":"☑️ Xabarlarni qadash\n",
        "don_killed":"🤵🏻 Sizning Don vafot etdi.\nEndi siz yangi Don bo'ldingiz!",
        "don_become":"🤵🏻 Don halok bo'ldi, endi mafialardan biri yangi Don bo'ldi!",
        "don_notify":"🤵🏻 Sizning yangi Don: <a href='tg://user?id={new_don_id}'>{first_name}</a>",
        "mafia_target":"Mafiyaning ovoz berishi yakunlandi\nMafialar {mafia_target} 💀 shavqatsizlarcha o'ldirdi.",
        "u_killed":"<b>Sizni o'ldirishdi :(</b>\nSiz bu yerdan o'lim oldi xabar qoldirishingiz mumkin",
        "u_saved": "<b>Sizni {protector_role_label} qutqardi!</b>\nSiz tirik qoldingiz!",
        "someone_interested":"Kimdir rolingizga qiziqdi...",
        "com_check_result":"<a href='tg://user?id={com_check_target}'>{target_name}</a> - {visible_role_text}",
        "daydi_report": "🧙🏼‍♂️ Tunda siz shisha uchun <a href='tg://user?id={daydi_house_id}'>{house_owner}</a> ga keldingiz va u yerda {visitors} ni ko'rdingiz.",
        "daydi_report_no_visitors": "🧙🏼‍♂️ Tunda siz <a href='tg://user?id={daydi_house_id}'>{house_owner}</a> dan shishalarni oldingiz va orqangizga qaytdingiz. Shubxali narsa sodir bo'lmadi.",
        "lover_blocked":"'Sen men bilan hamma narsani unut...', - deya kuyladi 💃🏼 <b>Ma'shuqa</b>",
        "win_report": "🏆 O'yin tugadi!\n{role_text} rolida g‘alaba qozondingiz!\n💵 Mukofot: {reward}\n\n{user_link}\n\n💵 Pullar: {coins}\n💎 Toshlar: {stones}\n🛡 Ximoya: {protection}\n📂 Hujjatlar: {docs}\n\n@MafiaRedDonOfficial obunachilari 2x bonus oladi!",
        "lose_report":  "🎮 O'yin tugadi!\nIshtirok uchun mukofot: {reward} 💵\n\n{user_link}\n\n💵 Pullar: {coins}\n💎 Toshlar: {stones}\n🛡 Ximoya: {protection}\n📂 Hujjatlar: {docs}\n\n@MafiaRedDonOfficial obunachilari 2x bonus oladi!",
        "title": "O'yin tugadi!",
        "winner": "G'olib: {winner}",
        "winners": "G'oliblar:",
        "others": "Qolgan o'yinchilar:",
        "no_one": "    (yo'q)",
        "duration": "O'yin: {time} davom etdi",
        "night_caption":"<b>🌃 Tun\nKo'chaga faqat jasur va qo'rqmas odamlar chiqishdi. Ertalab tirik qolganlarni sanaymiz..</b>",
        "alive_players":"<b>Tirik o'yinchilar:</b>",
        "1_min_day_start":"\n<b>Tonggacha 1 daqiqa qoldii!</b>",
        "don_choose":"🤵🏻 Mafia navbatdagi o'ljasini tanladi...",
        "don_not_choose":"🚷 🤵🏻 Don hech kimni o'ldirmaslikni afzal ko'rdi.",
        "day_start": "<b>🏙 {day}-kun\nQuyosh chiqdi, ammo tun orqasida nima bo‘lganini faqat bir necha kishi biladi...</b>",
        "no_night_deaths":"🧐 Ishonish qiyin tunda hech kim o'lmadi...",
        "from_them":"\nUlardan:\n\n",
        "peace_roles":"<b>Tinch axolilar - {count}\n {roles}</b>\n\n",
        "mafia_roles":"<b>Mafialar - {count}\n {roles}</b>\n\n",
        "debate_time":"\n\n<b>Tunda bo'lgan xodisalarni muxokama qilishning ayni vaqti...</b>",
        "start_voting":"<b>Aybdorlarni aniqlash va jazolash vaqti keldi.\nOvoz berish uchun 45 sekund</b>",
        "hang_prompt":"<b>Aybdorlarni izlash vaqti keldi!\nKimni osishni xohlaysiz?</b>",
        "vote_end":"<b>Ovoz berish yakunlandi.\nOvoz berish janjalga aylanib ketdi... Xamma uy-uyiga tarqaldi...</b>",
        "no_consenus":"<b>Aholi kelisha olmadi ({yes} 👍 | {no} 👎 )...\nKelisha olmaslik oqibatida hech kim osilmadi...</b>",
        "voted_user":"<b>Rostan ham ham <a href='tg://user?id={tg_id}'>{first_name}</a> ni osmoqchimisiz?</b>",
        "confirm_hang":"<b>Rostan ham ham <a href='tg://user?id={tg_id}'>{first_name}</a> ni osmoqchimisiz?\n\nOvoz berish tugadi.</b>",
        "hang_protect":"<b>Ovoz berish natijalari:\n\n{yes} 👍  |  {no} 👎\n\n<a href='tg://user?id={tg_id}'>{first_name}</a> - ni osishdan ximoyasi bor va u osilmadi! :)</b>",
        "hang_no_protect":"<b>Ovoz berish natijalari:\n\n{yes} 👍  |  {no} 👎\n\n<a href='tg://user?id={tg_id}'>{first_name}</a> - ni osamiz! :)</b>",
        "hanged":"<a href='tg://user?id={tg_id}'>{first_name}</a> - {role_label} edi!!",
        "game_not_active":"Kechirasiz, o'yin allaqachon boshlandi.",
        "already_in_game":"Sabr qiling siz o'yindasiz! Tushunyapsizmi? O'yinda! :)",
        "joined_game":"✅ Tabriklaymiz! Siz <b> {group_name} </b>guruhda o'yinga qo'shildingiz.",
        "greating_message":"Salom! <code>{first_name}</code>\nMen 🤵🏻Mafia o'yinini rasmiy botiman.",
        "use_game_command":"O'yin boshlash uchun /game buyrug'idan foydalaning.",
        "user_profile":"👤 <code>{first_name}</code>\n\n💶 Pullar: {coin}\n💎 Olmoslar: {stones}\n\n🛡 Ximoya: {protection}\n🎗️ Osilishdan ximoya: {hang_protect}\n📂 Hujjatlar: {docs}\n🔰 Geroy ximoyasi: {geroy_protect}\n\n🎯G'alaba: {wins}\n🎲 Barcha o'yinlar: {all_played}\n\n🃏 Faol ro'llar:\n{text}",
        "send_money":"ga {amount} 💵 yubordi.",
        "send_stone":"ga {amount} 💎 yubordi.",
        "left_game":"<a href='tg://user?id={telegram_id}'> {first_name}</a>Bu shaharning yovuzliklariga chiday olmadi va o'zini osib qo'ydi. U {role_label_text} edi.",
        "59_left":"⏳ Ro'yxatdan o'tishga 59 soniya qoldi!",
        "29_left":"⏳ Ro'yxatdan o'tishga 29 soniya qoldi!",
        "not_enough_players":"O'yinni boshlash uchun o'yinchilar yetarli emas...\n\nMinimal o'yinchilar soni - 4",
        "game_started":"O'yin boshlandi!\nBir necha soniya ichida bot sizga rol va uning tavsifi bilan shaxsiy xabar yuboradi.",
        "trial_expired":"❌ Guruhning obuna muddati tugagan.\nDavom ettirish uchun admin bilan bog‘laning.\n\nAdmin : @RedDon_Mafia",
        "registration_started":"Ro'yxatdan o'tish boshlandi",
        "registration_started_notify":"⏰ Eslatma!\n\n📢 Guruhda yangi o'yin uchun ro'yxatdan o'tish boshlandi.\n",
        "registration_stopped":"🛑 Ro'yxatdan o'tish to'xtatildi.",
        "registration_extended":"O'yin ro‘yxatga olish vaqti +30 sekundga uzaytirildi!\n",
        "time_left":"O'yin boshlanishiga {minutes} minut {seconds} sekund qoldi",
        "no_active_game":"❗ Hozir bu chatda active o'yin yo'q.",
        "game_stopped":"🛑 O'yin majburan to'xtatildi.",
        "top_daily":"🏆 Guruhda top reyting (kunlik)",
        "top_weekly":"🏆 Guruhda top reyting (haftalik)",
        "top_monthly":"🏆 Guruhda top reyting (oylik)",
        "mafia_companions":"Sheriklaringizni eslab qoling:",
        "no":"Yo'q",
        "active_role_used":"🎭 Faol roldan foydalanildi",
        "dance_party":"🥲 Siz Mashuqa bilan vaqtni chog' o'tkazing",
        "no_write_game_time":"🥲 O'yin vaqti sizga yozishga ruxsat yoq!\n🔈 45 sekundga mute qilindingiz.",
        "last_wish_message":"{role_label_text} <a href='tg://user?id={tg_id}'>{first_name}</a> ning so'ngi so'zlari quyidagicha edi:\n\n{text}",
        "last_wish_send":"✅ Sizning so'ngi so'zlaringiz guruhga yuborildi.",
        "buy_stone_group":"💎 Olmos sotib olish",
        "buy_money_group":"💶 Pul sotib olish",
        "buy_stone_group_desc":"Sotib olishdan avval hisobingizda yetarlicha stars mavjudligini tekshiring.",
        "payment_method_choose":"Kerakli tolov tizimini tanlang:",
        "buy_role":"🎭 Rol sotib olish uchun quyidagi ro'llardan birini tanlang:",
        "not_enough_stones":"💎 Olmos yetarli emas!",
        "not_enough_money":"💵 Hisobingizda yetarli pul yo'q!",
        "role_bought":"✅ Siz rol sotib oldingiz!",
        "buy_another_role":"🎭 Yana rol sotib olasizmi?",
        "roles_list":"🎎 Mavjud rollar ro'yxati\n\nUning tavsifini ko'rish uchun rol nomini bosing",
        "money_in_money":"💶 Pulni naqd pul orqali olish\n\nNarxlar:\n\n{money}\n\nTo'lovni amalga oshirish uchun @RedDon_Mafia ga yozing.",
        "stone_in_money":"💎 Olmosni naqd pul orqali olish\n\nNarxlar:\n\n{stone}\n\nTo'lovni amalga oshirish uchun @RedDon_Mafia ga yozing.",
        "money_in_stars":"💶 Pulni yulduzlar evaziga olish\nKerakli miqdorni tanlang:",
        "stone_in_stars":"💎 Olmosni yulduzlar evaziga olish\nKerakli miqdorni tanlang:",
        "choose_quantity":"Kerakli miqdorni tanlang:",
        "action_choose":"ni tanladingiz.",
        "no_go_doc":"🚷 👨🏼‍⚕️ Shifokor hech qayoqqa bormaslikni afzal ko'rdi.",
        "go_doc":"👨🏼‍⚕️ Shifokor tungi navbatchilikka ketdi...",
        "action_no_choose":"Siz hech kimni tanlamadingiz.",
        "late":"Siz kechikdingiz.",
        "daydi_no_go":"🚷 🧙🏼‍♂️ Daydi hech qayoqqa bormaslikni afzal ko'rdi.",
        "daydi_go":"🧙🏼‍♂️ Daydi kimnikigadir shisha olish uchun ketdi...",
        "com_no_go":"🚷 🕵️‍ Komissar bugun dam olishni xohladi.",
        "com_shoot":"🕵️‍ Komissar Katani pistoletini o'qladi...",
        "com_check":"🕵️‍ Komissar Katani yovuzlarni qidirishga ketdi...",
        "lover_no_go":"🚷 💃🏼 Ma'shuqa hech kimni kutmayapti.",
        "lover_go":"💃🏼 Ma'shuqa qandaydir mehmonni kutayapti...",
        "adv_no_go":"🚷 👨🏻‍💻 Advokat hech kimni himoya qilmaslikni afzal ko'rdi.",
        "adv_go":"👨🏻‍💻 Advokat o'z mijozini himoya qilishga ketdi...",
        "hang_action":"Aybdorlarni izlash vaqti keldi!\nKimni osishni xohlaysiz?",
        "no_hang_choose":"hech kimni osmaslikni taklif qildi",
        "hang_choose":"ga ovoz berdi",
        "dead_cant_vote":"⚠️ O'lik o'yinchilar ovoz bera olmaydi!",
        "no_player":"❌ Siz ushbu o'yinda ishtirok etmayapsiz!",
        "cant_vote_self":"❌ O'zingizga ovoz bera olmaysiz!",
        "lover_waiting":"❌ Sizni sevgilingiz kutmoqda, ovoz bera olmaysiz!",
        "vote_accepted":"👍 Ovozingiz qabul qilindi.",
        "stone_ended":"❌ Olmos tugadi!",
        "stone_already_taken":"⚠️ Siz allaqachon olgansiz!",
        "stone_not_in_game":"❌ Siz o‘yinda yo‘qsiz. Faqat o'yindagilar oladi!",
        "user_not_found":"❌ Foydalanuvchi topilmadi!",
        "join_game":"🤵🏻 Qo'shilish",
        "view_role":"🎭 Rolni ko'rish",
        "go_to_bot":"🤖 Botga o'tish",
        "vote":"🗳 Ovoz berish",
        "already_in_another_game":"❌ Siz allaqachon boshqa o'yinda ishtirok etmoqdasiz!",
}

ru_texts ={
    "ROLES_CHOICES" : [
    ("peace", "👨🏼 Мирный житель"),
    ('nogiron',"👨🏻‍🦼‍➡️ Неполноценный"), 
    ('suid', "🤦🏻 Самоубийца"),
    ("doc", "👨🏼‍⚕️ Доктор"),
    ("daydi", "🧙🏼‍♂️ Бродяга"),
    ("com", "🕵🏻‍♂️ Комиссар Катани"),
    ("kam", "💣 Камикадзе"),
    ("lover", "💃🏻 Любовница"),
    ("mafia", "🤵🏼 Мафия"),
    ("don", "🤵🏻 Дон"),
    ("adv", "👨🏻‍💻 Адвокат"),
    ("back_main", "⬅️ Назад"),
],
    
"WINNER_LABEL" : {
    "peace": "👨🏼 Мирные жители",
    "mafia": "🤵🏻 Мафия",
},

"DESCRIPTIONS" : {
    "peace": "🧑🏻 Мирный житель. Ваша задача — найти мафию и помочь повесить их на дневном голосовании.",
    "nogiron":"👨🏻‍🦼‍➡️ Вы голосуете за мафию только в рамках беспартийного процесса голосования",
    "don": "🤵🏻 Дон. Глава мафии. Каждую ночь выбирает жертву, и вся мафия подчиняется его решению.",
    "mafia": "🤵🏼 Мафия. Работаете с Доном и выбираете жертв ночью. Если Дон погибнет, можете занять его место.",
    "com": "🕵🏻 Комиссар. Каждую ночь проверяет игрока и может застрелить подозрительного. Защитник мирных.",
    "doc": "🧑🏻‍⚕️ Доктор. Каждую ночь можете спасти одного игрока от смерти.",
    "lover": "💃🏻 Любовница. Блокирует выбранного игрока на одну ночь.",
    "adv": "👨🏻‍💼 Адвокат. На стороне мафии. Делает мафиози мирным в глазах Комиссара.",
    "suid": "🤦🏻 Самоубийца. Если вас повесят днём, вы мгновенно выигрываете.",
    "daydi": "🧙🏻 Бродяга. Ночью посещает дом и может увидеть происходящее там.",
    "kam": "💣 Камикадзе. Если вас повесят, можете забрать одного игрока с собой.",
},
"ACTIONS" : {
    "don_kill": "🤵🏻 Мафия голосует за следующую жертву: ",
    "mafia_vote": "🤵🏻 Кого вы хотите убить этой ночью?",
    "adv_mask": "👨🏻‍💻 Какого мафиози скроем?",
    
    "doc_heal": "👨🏼‍⚕️ Кого будем лечить этой ночью?",
    "com_deside":" 🕵🏻‍♂️ Что вы будете делать этой ночью?",
    "com_check": "🔍 Кого проверим?",
    "com_shoot": "🔫 В кого стрелять?",
    "daydi_watch": "🧙🏼‍♂️ В чей дом пойдёте этой ночью?",
    "lover_block": "💃🏻 С кем проведёте ночь?",
    "kamikaze_blow": "💣 Кого взорвать?",
   
},

"punish_afk":"Ночью {role_label} <a href='tg://user?id={pid}'>{name}</a> был жестоко убит...\nПеред смертью он сказал:\n'Я больше никогда не буду спать во время игры-и-и-и!'",
"reg_started": "Регистрация началась",
"reg_list": "Зарегистрированные игроки:",
"total": "Всего {count} игроков",
"no_players": "Пока никто не зарегистрировался",
"bot_no_rights": "⚠️ У бота недостаточно прав администратора!\nЗдравствуйте! Я официальный бот игры Мафия.\n\nНеобходимы следующие разрешения:\n",
"bot_no_rights_add":"☑️ Назначить администратором\n☑️ Удалять сообщения\n☑️ Ограничивать участников\n☑️ Закреплять сообщения\n",
"bot_no_rights_delete":"☑️ Удалять сообщения\n",
"bot_no_rights_restrict":"☑️ Ограничивать участников\n",
"bot_no_rights_pin":"☑️ Закреплять сообщения\n",
"don_killed":"🤵🏻 Ваш Дон погиб.\nТеперь вы новый Дон!",
"don_notify":"🤵🏻 Новый Дон: <a href='tg://user?id={new_don_id}'>{first_name}</a>",
"mafia_target":"Голосование мафии завершено\nМафия жестоко убила {mafia_target} 💀.",
"u_killed":"<b>Вас убили :(</b>\nВы можете оставить последнее сообщение",
"u_saved": "<b>Вас спас {protector_role_label}!</b>\nВы выжили!",
"someone_interested":"Кто-то интересовался вашей ролью...",
"com_check_result":"<a href='tg://user?id={com_check_target}'>{target_name}</a> - {visible_role_text}",
"daydi_report": "🧙🏼‍♂️ Ночью вы посетили <a href='tg://user?id={daydi_house_id}'>{house_owner}</a> и увидели {visitors}.",
"daydi_report_no_visitors": "🧙🏼‍♂️ Вы посетили <a href='tg://user?id={daydi_house_id}'>{house_owner}</a>, ничего подозрительного.",
"lover_blocked":"'Забудь всё со мной...', пропела 💃🏼 <b>Любовница</b>",
"win_report": "🏆 Игра окончена!\nВы победили как {role_text}!\n💵 Награда: {reward}\n\n{user_link}\n\n💵 Деньги: {coins}\n💎 Алмазы: {stones}\n🛡 Защита: {protection}\n📂 Документы: {docs}\n\nПодписчики @MafiaRedDonOfficial получают 2x бонус!",
"lose_report":  "🎮 Игра окончена!\nНаграда за участие: {reward} 💵\n\n{user_link}\n\n💵 Деньги: {coins}\n💎 Алмазы: {stones}\n🛡 Защита: {protection}\n📂 Документы: {docs}\n\nПодписчики @MafiaRedDonOfficial получают 2x бонус!",
"title": "Игра окончена!",
"winner": "Победитель: {winner}",
"winners": "Победители:",
"others": "Оставшиеся игроки:",
"no_one": "    (нет)",
"duration": "Игра длилась: {time}",
"night_caption":"<b>🌃 Ночь\nНа улицу вышли только смелые. Утром посчитаем выживших..</b>",
"alive_players":"<b>Живые игроки:</b>",
"1_min_day_start":"\n<b>До рассвета осталась 1 минута!</b>",
"don_choose":"🤵🏻 Мафия выбрала жертву...",
"don_not_choose":"🚷 🤵🏻 Дон решил никого не убивать.",
"day_start": "<b>🏙 День {day}\nСолнце взошло, но лишь немногие знают, что было ночью...</b>",
"no_night_deaths":"🧐 Удивительно, но ночью никто не погиб...",
"from_them":"\nСреди них:\n\n",
"peace_roles":"<b>Мирные - {count}\n {roles}</b>\n\n",
"mafia_roles":"<b>Мафия - {count}\n {roles}</b>\n\n",
"debate_time":"\n\n<b>Время обсудить события ночи...</b>",
"start_voting":"<b>Время найти виновных.\nГолосование 45 секунд</b>",
"hang_prompt":"<b>Кого повесить?</b>",
"vote_end":"<b>Голосование окончено.\nНачался хаос... Все разошлись...</b>",
"no_consenus":"<b>Город не пришёл к согласию ({yes} 👍 | {no} 👎 )...\nНикого не повесили...</b>",
"voted_user":"<b>Вы уверены, что хотите повесить <a href='tg://user?id={tg_id}'>{first_name}</a>?</b>",
"confirm_hang":"<b>Вы уверены, что хотите повесить <a href='tg://user?id={tg_id}'>{first_name}</a>?\n\nГолосование завершено.</b>",
"hang_protect":"<b>Результаты голосования:\n\n{yes} 👍  |  {no} 👎\n\nУ <a href='tg://user?id={tg_id}'>{first_name}</a> была защита!</b>",
"hang_no_protect":"<b>Результаты голосования:\n\n{yes} 👍  |  {no} 👎\n\n<a href='tg://user?id={tg_id}'>{first_name}</a> будет повешен!</b>",
"hanged":"<a href='tg://user?id={tg_id}'>{first_name}</a> был {role_label}!!",
"game_not_active":"Извините, игра уже началась.",
"already_in_game":"Подождите, вы уже в игре! Понимаете? В игре! :)",
"joined_game":"✅ Поздравляем! Вы присоединились к игре в группе <b>{group_name}</b>.",
"greating_message":"Привет! <code>{first_name}</code>\nЯ официальный бот игры 🤵🏻 Мафия.",
"use_game_command":"Используйте команду /game, чтобы начать игру.",
"user_profile":"👤 <code>{first_name}</code>\n\n💶 Деньги: {coin}\n💎 Алмазы: {stones}\n\n🛡 Защита: {protection}\n🎗️ Защита от повешения: {hang_protect}\n📂 Документы: {docs}\n🔰 Геройская защита: {geroy_protect}\n\n🎯Победы: {wins}\n🎲 Все игры: {all_played}\n\n🃏 Активные роли:\n{text}",
"send_money":"отправил {amount} 💵.",
"send_stone":"отправил {amount} 💎.",
"left_game":"<a href='tg://user?id={telegram_id}'> {first_name}</a> не выдержал зла этого города и повесился. Его роль была {role_label_text}.",
"59_left":"⏳ До окончания регистрации 59 секунд!",
"29_left":"⏳ До окончания регистрации 29 секунд!",
"not_enough_players":"Недостаточно игроков для начала игры...\n\nМинимум игроков — 4",
"game_started":"Игра началась!\nЧерез несколько секунд бот отправит вам роль и описание в личные сообщения.",
"trial_expired":"❌ Срок подписки группы истёк.\nСвяжитесь с админом для продолжения.\n\nАдмин : @RedDon_Mafia",
"registration_started":"Регистрация началась",
"registration_started_notify":"⏰ Напоминание!\n\n📢 В группе началась регистрация на новую игру.\n",
"registration_stopped":"🛑 Регистрация остановлена.",
"registration_extended":"Время регистрации продлено на +30 секунд!\n",
"time_left":"До начала игры: {minutes} минут {seconds} секунд",
"no_active_game":"❗ В этом чате нет активной игры.",
"game_stopped":"🛑 Игра была принудительно остановлена.",
"top_daily":"🏆 Топ рейтинг в группе (день)",
"top_weekly":"🏆 Топ рейтинг в группе (неделя)",
"top_monthly":"🏆 Топ рейтинг в группе (месяц)",
"mafia_companions":"Запомните своих союзников:",
"no":"Нет",
"active_role_used":"🎭 Активная роль использована",
"dance_party":"🥲 Проведите время с Любовницей",
"no_write_game_time":"🥲 Вам нельзя писать во время игры!\n🔈 Вы замучены на 45 секунд.",
"last_wish_message":"Последние слова {role_label_text} <a href='tg://user?id={tg_id}'>{first_name}</a> были:\n\n{text}",
"last_wish_send":"✅ Ваши последние слова отправлены в группу.",
"buy_stone_group":"💎 Купить алмазы",
"buy_money_group":"💶 Купить деньги",
"buy_stone_group_desc":"Перед покупкой убедитесь, что у вас достаточно stars на балансе.",
"payment_method_choose":"Выберите способ оплаты:",
"buy_role":"🎭 Чтобы купить роль, выберите из списка ниже:",
"not_enough_stones":"💎 Недостаточно алмазов!",
"not_enough_money":"💵 Недостаточно денег на балансе!",
"role_bought":"✅ Вы купили роль!",
"buy_another_role":"🎭 Хотите купить ещё роль?",
"roles_list":"🎎 Список доступных ролей\n\nНажмите на роль, чтобы увидеть описание",
"money_in_money":"💶 Вывод денег наличными\n\nЦены:\n\n{money}\n\nДля оплаты свяжитесь с @RedDon_Mafia.",
"stone_in_money":"💎 Вывод алмазов наличными\n\nЦены:\n\n{stone}\n\nДля оплаты свяжитесь с @RedDon_Mafia.",
"money_in_stars":"💶 Получить деньги за stars\nВыберите нужное количество:",
"stone_in_stars":"💎 Получить алмазы за stars\nВыберите нужное количество:",
"choose_quantity":"Выберите нужное количество:",
"action_choose":"вы выбрали.",
"no_go_doc":"🚷 👨🏼‍⚕️ Доктор решил никуда не идти.",
"go_doc":"👨🏼‍⚕️ Доктор отправился на ночное дежурство...",
"action_no_choose":"Вы никого не выбрали.",
"late":"Вы опоздали.",
"daydi_no_go":"🚷 🧙🏼‍♂️ Бродяга решил никуда не идти.",
"daydi_go":"🧙🏼‍♂️ Бродяга пошёл к кому-то за бутылками...",
"com_no_go":"🚷 🕵️ Комиссар решил отдохнуть.",
"com_shoot":"🕵️ Комиссар Катани зарядил пистолет...",
"com_check":"🕵️ Комиссар Катани отправился искать зло...",
"lover_no_go":"🚷 💃🏼 Любовница никого не ждёт.",
"lover_go":"💃🏼 Любовница ждёт гостя...",
"adv_no_go":"🚷 👨🏻‍💻 Адвокат решил никого не защищать.",
"adv_go":"👨🏻‍💻 Адвокат пошёл защищать клиента...",
"lab_no_go":"🚷 👨‍🔬 Лаборант решил никому не давать лекарство.",
"lab_go":"👨‍🔬 Лаборант готовит лекарство...",
"don_become":"🤵🏻 Дон мертв, теперь один из мафиози стал новым Доном!",
"hang_action":"Кого повесить?",
"no_hang_choose":"предложил никого не вешать",
"hang_choose":"проголосовал за повешение",
"dead_cant_vote":"⚠️ Мёртвые игроки не могут голосовать!",
"no_player":"❌ Вы не участвуете в игре!",
"cant_vote_self":"❌ Нельзя голосовать за себя!",
"lover_waiting":"❌ Вас ждёт любовница, голосовать нельзя!",
"vote_accepted":"👍 Ваш голос принят.",
"stone_ended":"❌ Алмазы закончились!",
"stone_already_taken":"⚠️ Вы уже получили!",
"stone_not_in_game":"❌ Вы не в игре.",
"user_not_found":"❌ Пользователь не найден!",
"join_game": "🤵🏻 Присоединиться",
"view_role": "🎭 Посмотреть роль",
"go_to_bot": "🤖 Перейти к боту",
"vote": "🗳 Голосовать",
"already_in_another_game":"⚠️ Вы уже участвуете в другой игре!",

}


en_texts ={
    "ROLES_CHOICES" : [
    ("peace", "👨🏼 Civilian"),
    ('nogiron',"👨🏻‍🦼‍➡️ Disabled"),
    ('suid', "🤦🏻 Suidside" ),
    ("doc", "👨🏼‍⚕️ Doctor"),
    ("daydi", "🧙🏼‍♂️ Wanderer"),
    ("com", "🕵🏻‍♂️ Commissioner Katani"),
    ("kam", "💣 Kamikaze"),
    ("lover", "💃🏻 Lover"),
    
    ("mafia", "🤵🏼 Mafia"),
    ("don", "🤵🏻 Don"),
    ("adv", "👨🏻‍💻 Lawyer"),
    ("back_main", "⬅️ Back"),
],
    "WINNER_LABEL" : {
    "peace": "👨🏼 Civilians",
    "mafia": "🤵🏻 Mafia",
},

"DESCRIPTIONS" : {
    "peace": "🧑🏻 Civilian. Your task is to find the mafia and help lynch them during the day vote.",
    "nogiron":"👨🏻‍🦼‍➡️ Disabled You are only voting for the mafia in a non-partisan voting process",
    "don": "🤵🏻 Don. Leader of the mafia. Each night you choose a victim and the whole mafia follows your decision.",
    "mafia": "🤵🏼 Mafia. You work with the Don and choose victims at night. If the Don dies, you may take his place.",
    "com": "🕵🏻 Commissioner. Checks a player every night and may shoot if suspicious. Protector of civilians.",
    "doc": "🧑🏻‍⚕️ Doctor. Each night you can save one player from death. The hope of civilians.",
    "lover": "💃🏻 Lover. Blocks the chosen player for one night, they cannot perform any action.",
    "adv": "👨🏻‍💼 Lawyer. On mafia’s side. Makes a chosen mafia member appear as civilian to the Commissioner.",
    "suid": "🤦🏻 Suicide. If you are lynched during the day, you instantly win regardless of the game result.",
    "daydi": "🧙🏻 Wanderer. Visits a house at night and can witness events happening there.",
    "kam": "💣 Kamikaze. If lynched, you can take one player with you.",
   
},

"ACTIONS" : {
    "don_kill": "🤵🏻 Mafia is voting for the next victim: ",
    "mafia_vote": "🤵🏻 Who do you vote to kill tonight?",
    "adv_mask": "👨🏻‍💻 Which mafia member should we hide?",

    "doc_heal": "👨🏼‍⚕️ Who shall we heal tonight?",
    "com_deside":" 🕵🏻‍♂️ What will you do tonight?",
    "com_check": "🔍 Who shall we check?",
    "com_shoot": "🔫 Who shall we shoot?",
    "daydi_watch": "🧙🏼‍♂️ Whose house will you visit tonight for bottles?",
    "lover_block": "💃🏻 Who will you spend the night with?",

    "kamikaze_blow": "💣 Who shall we blow up?",
   
},

"punish_afk":"At night {role_label} <a href='tg://user?id={pid}'>{name}</a> was brutally killed...\nBefore dying, they said:\n'I will never sleep during the game agaaaain!'",
"reg_started": "Registration started",
"reg_list": "Registered players:",
"total": "Total {count} players",
"no_players": "No one has registered yet",
"bot_no_rights": "⚠️ The bot does not have enough admin rights!\nHello! I am the official Mafia game bot.\n\nThe following permissions are required:\n",
"bot_no_rights_add":"☑️ Make admin\n☑️ Delete messages\n☑️ Restrict members\n☑️ Pin messages\n",
"bot_no_rights_delete":"☑️ Delete messages\n",
"bot_no_rights_restrict":"☑️ Restrict members\n",
"bot_no_rights_pin":"☑️ Pin messages\n",
"don_killed":"🤵🏻 Your Don has died.\nYou are the new Don now!",
"don_become":"🤵🏻 The Don is dead, now one of the mafias has become the new Don!",
"don_notify":"🤵🏻 Your new Don: <a href='tg://user?id={new_don_id}'>{first_name}</a>",
"mafia_target":"Mafia vote ended\nMafia brutally killed {mafia_target} 💀.",
"u_killed":"<b>You were killed :(</b>\nYou can leave a last message here",
"u_saved": "<b>You were saved by {protector_role_label}!</b>\nYou survived!",
"someone_interested":"Someone was interested in your role...",
"com_check_result":"<a href='tg://user?id={com_check_target}'>{target_name}</a> - {visible_role_text}",
"daydi_report": "🧙🏼‍♂️ At night you visited <a href='tg://user?id={daydi_house_id}'>{house_owner}</a> and saw {visitors}.",
"daydi_report_no_visitors": "🧙🏼‍♂️ You visited <a href='tg://user?id={daydi_house_id}'>{house_owner}</a> and nothing suspicious happened.",
"lover_blocked":"'Forget everything with me...', sang 💃🏼 <b>Lover</b>",
"win_report": "🏆 Game over!\nYou won as {role_text}!\n💵 Reward: {reward}\n\n{user_link}\n\n💵 Coins: {coins}\n💎 Stones: {stones}\n🛡 Protection: {protection}\n📂 Documents: {docs}\n\nSubscribers of @MafiaRedDonOfficial get 2x bonus!",
"lose_report":  "🎮 Game over!\nParticipation reward: {reward} 💵\n\n{user_link}\n\n💵 Coins: {coins}\n💎 Stones: {stones}\n🛡 Protection: {protection}\n📂 Documents: {docs}\n\nSubscribers of @MafiaRedDonOfficial get 2x bonus!",
"title": "Game over!",
"winner": "Winner: {winner}",
"winners": "Winners:",
"others": "Remaining players:",
"no_one": "    (none)",
"duration": "Game lasted: {time}",
"night_caption":"<b>🌃 Night\nOnly the brave walked the streets. We’ll count survivors in the morning..</b>",
"alive_players":"<b>Alive players:</b>",
"1_min_day_start":"\n<b>1 minute left until dawn!</b>",
"don_choose":"🤵🏻 Mafia chose the next victim...",
"don_not_choose":"🚷 🤵🏻 Don chose not to kill anyone.",
"day_start": "<b>🏙 Day {day}\nThe sun rose, but only a few know what happened at night...</b>",
"no_night_deaths":"🧐 Hard to believe, no one died tonight...",
"from_them":"\nAmong them:\n\n",
"peace_roles":"<b>Civilians - {count}\n {roles}</b>\n\n",
"mafia_roles":"<b>Mafia - {count}\n {roles}</b>\n\n",
"debate_time":"\n\n<b>Time to discuss what happened at night...</b>",
"start_voting":"<b>Time to find and punish the guilty.\nVoting lasts 45 seconds</b>",
"hang_prompt":"<b>Time to find the guilty!\nWho do you want to lynch?</b>",
"vote_end":"<b>Voting ended.\nVoting turned into chaos... Everyone went home...</b>",
"no_consenus":"<b>The town couldn't agree ({yes} 👍 | {no} 👎 )...\nNo one was lynched...</b>",
"voted_user":"<b>Do you really want to lynch <a href='tg://user?id={tg_id}'>{first_name}</a>?</b>",
"confirm_hang":"<b>Do you really want to lynch <a href='tg://user?id={tg_id}'>{first_name}</a>?\n\nVoting ended.</b>",
"hang_protect":"<b>Voting results:\n\n{yes} 👍  |  {no} 👎\n\n<a href='tg://user?id={tg_id}'>{first_name}</a> had lynch protection and survived! :)</b>",
"hang_no_protect":"<b>Voting results:\n\n{yes} 👍  |  {no} 👎\n\n<a href='tg://user?id={tg_id}'>{first_name}</a> will be lynched! :)</b>",
"hanged":"<a href='tg://user?id={tg_id}'>{first_name}</a> was {role_label}!!",
"game_not_active":"Sorry, the game has already started.",
"already_in_game":"Be patient, you are already in the game! Understand? In the game! :)",
"joined_game":"✅ Congratulations! You joined the game in group <b>{group_name}</b>.",
"greating_message":"Hello! <code>{first_name}</code>\nI am the official 🤵🏻 Mafia game bot.",
"use_game_command":"Use the /game command to start the game.",
"send_money":"sent {amount} 💵.",
"send_stone":"sent {amount} 💎.",
"left_game":"<a href='tg://user?id={telegram_id}'> {first_name}</a> could not handle the evil of this city and hanged themselves. They were {role_label_text}.",
"59_left":"⏳ 59 seconds left to register!",
"29_left":"⏳ 29 seconds left to register!",
"not_enough_players":"Not enough players to start the game...\n\nMinimum players required - 4",
"game_started":"The game has started!\nIn a few seconds, the bot will send you your role and description via private message.",
"trial_expired":"❌ Group subscription has expired.\nContact admin to continue.\n\nAdmin : @RedDon_Mafia",
"registration_started":"Registration started",
"registration_started_notify":"⏰ Reminder!\n\n📢 Registration for a new game has started in the group.\n",
"registration_stopped":"🛑 Registration stopped.",
"registration_extended":"Game registration time extended by +30 seconds!\n",
"time_left":"Time until game starts: {minutes} minutes {seconds} seconds",
"no_active_game":"❗ There is no active game in this chat.",
"game_stopped":"🛑 The game was forcibly stopped.",
"top_daily":"🏆 Top ranking in the group (daily)",
"top_weekly":"🏆 Top ranking in the group (weekly)",
"top_monthly":"🏆 Top ranking in the group (monthly)",
"mafia_companions":"Remember your teammates:",
"no":"No",
"active_role_used":"🎭 Active role used",
"dance_party":"🥲 Spend time with your Lover",
"no_write_game_time":"🥲 You are not allowed to write during game time!\n🔈 You have been muted for 45 seconds.",
"last_wish_message":"{role_label_text} <a href='tg://user?id={tg_id}'>{first_name}</a>'s last words were:\n\n{text}",
"last_wish_send":"✅ Your last words have been sent to the group.",
"buy_stone_group":"💎 Buy diamonds",
"buy_money_group":"💶 Buy money",
"buy_stone_group_desc":"Before buying, make sure you have enough stars in your balance.",
"payment_method_choose":"Choose the payment method:",
"buy_role":"🎭 To buy a role, select one from the list below:",
"not_enough_stones":"💎 Not enough diamonds!",
"not_enough_money":"💵 Not enough money in your balance!",
"role_bought":"✅ You bought a role!",
"buy_another_role":"🎭 Want to buy another role?",
"roles_list":"🎎 List of available roles\n\nClick a role name to see its description",
"money_in_money":"💶 Withdraw money in cash\n\nPrices:\n\n{money}\n\nTo make a payment, contact @RedDon_Mafia.",
"stone_in_money":"💎 Withdraw diamonds in cash\n\nPrices:\n\n{stone}\n\nTo make a payment, contact @RedDon_Mafia.",
"money_in_stars":"💶 Get money for stars\nSelect the required amount:",
"stone_in_stars":"💎 Get diamonds for stars\nSelect the required amount:",
"choose_quantity":"Select the required amount:",
"action_choose":"you selected.",
"no_go_doc":"🚷 👨🏼‍⚕️ Doctor chose not to go anywhere.",
"go_doc":"👨🏼‍⚕️ Doctor went on night duty...",
"action_no_choose":"You didn’t choose anyone.",
"late":"You are late.",
"daydi_no_go":"🚷 🧙🏼‍♂️ Wanderer chose not to go anywhere.",
"daydi_go":"🧙🏼‍♂️ Wanderer went to someone’s house for bottles...",
"com_no_go":"🚷 🕵️ Commissioner chose to rest tonight.",
"com_shoot":"🕵️ Commissioner Katani loaded his pistol...",
"com_check":"🕵️ Commissioner Katani went to search for evil...",
"lover_no_go":"🚷 💃🏼 Lover is not waiting for anyone.",
"lover_go":"💃🏼 Lover is waiting for a guest...",
"adv_no_go":"🚷 👨🏻‍💻 Lawyer chose not to protect anyone.",
"adv_go":"👨🏻‍💻 Lawyer went to defend his client...",
"hang_action":"Time to find the guilty!\nWho do you want to lynch?",
"no_hang_choose":"suggested not to lynch anyone",
"hang_choose":"voted to lynch",
"dead_cant_vote":"⚠️ Dead players cannot vote!",
"no_player":"❌ You are not in this game!",
"cant_vote_self":"❌ You cannot vote for yourself!",
"lover_waiting":"❌ Your lover is waiting for you, you cannot vote!",
"vote_accepted":"👍 Your vote has been accepted.",
"stone_ended":"❌ Diamonds are finished!",
"stone_already_taken":"⚠️ You have already taken!",
"stone_not_in_game":"❌ You are not in the game. Only players can receive!",
"user_not_found":"❌ User not found!",
"join_game": "🤵🏻 Join",
"view_role": "🎭 View role",
"go_to_bot": "🤖 Go to bot",
"vote": "🗳 Vote",
"already_in_another_game":"❌ You are already in another game! Please wait for it to finish.",

}

tr_texts ={
    "ROLES_CHOICES" : [
    ("peace", "👨🏼 Sivil Vatandaş"),
    ('nogiron','👨🏻‍🦼‍➡️ Engelli'),
    ('suid', "🤦🏻 İntihar"),
    ("doc", "👨🏼‍⚕️ Doktor"),
    ("daydi", "🧙🏼‍♂️ Serseri"),
    ("com", "🕵🏻‍♂️ Komiser Katani"),
    ("kam", "💣 Kamikaze"),
    ("lover", "💃🏻 Sevgili"),
    ("mafia", "🤵🏼 Mafya"),
    ("don", "🤵🏻 Don"),
    ("adv", "👨🏻‍💻 Avukat"),
    ("back_main", "⬅️ Geri"),
],
"WINNER_LABEL" : {
    "peace": "👨🏼 Siviller",
    "mafia": "🤵🏻 Mafya",
},

"DESCRIPTIONS" : {
    "peace": "🧑🏻 Sivil. Göreviniz mafyayı bulmak ve gündüz oylamasında asılmalarına yardım etmek.",
    "nogiron":"👨🏻‍🦼‍➡️ Engelli, tarafsız bir oylama sürecinde sadece mafyaya oy veriyorsunuz.",
    "don": "🤵🏻 Don. Mafyanın lideri. Her gece kurbanı seçer ve tüm mafya kararına uyar.",
    "mafia": "🤵🏼 Mafya. Don ile birlikte çalışırsınız. Don ölürse yerine geçebilirsiniz.",
    "com": "🕵🏻 Komiser. Her gece bir oyuncuyu kontrol eder, şüpheliyse vurabilir.",
    "doc": "🧑🏻‍⚕️ Doktor. Her gece bir oyuncuyu ölümden kurtarabilir.",
    "lover": "💃🏻 Sevgili. Seçilen oyuncuyu bir gece engeller.",
    "adv": "👨🏻‍💼 Avukat. Mafya tarafında. Mafyayı komiserin gözünde sivil gösterir.",
    "suid": "🤦🏻 İntihar. Gündüz asılırsanız oyunu hemen kazanırsınız.",
    "daydi": "🧙🏻 Serseri. Gece bir evi ziyaret edip olaylara tanık olabilir.",
    "kam": "💣 Kamikaze. Asılırsanız bir oyuncuyu yanınızda götürürsünüz.",
},
"ACTIONS" : {
    "don_kill": "🤵🏻 Mafya bir sonraki kurban için oy veriyor: ",
    "mafia_vote": "🤵🏻 Bu gece kimi öldürmek istiyorsunuz?",
    "adv_mask": "👨🏻‍💻 Hangi mafyayı gizleyelim?",

    "doc_heal": "👨🏼‍⚕️ Bu gece kimi iyileştirelim?",
    "com_deside":" 🕵🏻‍♂️ Bu gece ne yapacaksınız?",
    "com_check": "🔍 Kimi kontrol edelim?",
    "com_shoot": "🔫 Kimi vuralım?",
    "daydi_watch": "🧙🏼‍♂️ Bu gece kimin evine gideceksiniz?",
    "lover_block": "💃🏻 Bu gece kiminle olacaksınız?",

    
    "kamikaze_blow": "💣 Kimi patlatalım?",
   
},

"punish_afk":"Gece {role_label} <a href='tg://user?id={pid}'>{name}</a> vahşice öldürüldü...\nÖlmeden önce şöyle dedi:\n'Oyun sırasında bir daha asla uyumayacağım!'",
"reg_started": "Kayıt başladı",
"reg_list": "Kayıtlı oyuncular:",
"total": "Toplam {count} oyuncu",
"no_players": "Henüz kimse kayıt olmadı",
"bot_no_rights": "⚠️ Botun yeterli yönetici izni yok!\nMerhaba! Ben resmi Mafia oyun botuyum.\n\nŞu izinler gerekli:\n",
"bot_no_rights_add":"☑️ Yönetici yap\n☑️ Mesaj sil\n☑️ Üyeleri kısıtla\n☑️ Mesaj sabitle\n",
"bot_no_rights_delete":"☑️ Mesaj sil\n",
"bot_no_rights_restrict":"☑️ Üyeleri kısıtla\n",
"bot_no_rights_pin":"☑️ Mesaj sabitle\n",
"don_killed":"🤵🏻 Donunuz öldü.\nArtık yeni Don sizsiniz!",
"don_notify":"🤵🏻 Yeni Don: <a href='tg://user?id={new_don_id}'>{first_name}</a>",
"mafia_target":"Mafya oylaması bitti\nMafya {mafia_target} kişisini acımasızca öldürdü 💀.",
"u_killed":"<b>Öldürüldünüz :(</b>\nSon mesaj bırakabilirsiniz",
"u_saved": "<b>Sizi {protector_role_label} kurtardı!</b>\nHayatta kaldınız!",
"someone_interested":"Birisi rolünüzle ilgilendi...",
"com_check_result":"<a href='tg://user?id={com_check_target}'>{target_name}</a> - {visible_role_text}","daydi_report": "🧙🏼‍♂️ Gece <a href='tg://user?id={daydi_house_id}'>{house_owner}</a> evine gittiniz ve {visitors} gördünüz.",
"daydi_report_no_visitors": "🧙🏼‍♂️ <a href='tg://user?id={daydi_house_id}'>{house_owner}</a> evine gittiniz, şüpheli bir şey olmadı.",
"lover_blocked":"'Benimle her şeyi unut...', diye şarkı söyledi 💃🏼 <b>Sevgili</b>",
"win_report": "🏆 Oyun bitti!\n{role_text} olarak kazandınız!\n💵 Ödül: {reward}\n\n{user_link}\n\n💵 Para: {coins}\n💎 Elmas: {stones}\n🛡 Koruma: {protection}\n📂 Belgeler: {docs}\n\n@MafiaRedDonOfficial aboneleri 2x bonus alır!",
"lose_report":  "🎮 Oyun bitti!\nKatılım ödülü: {reward} 💵\n\n{user_link}\n\n💵 Para: {coins}\n💎 Elmas: {stones}\n🛡 Koruma: {protection}\n📂 Belgeler: {docs}\n\n@MafiaRedDonOfficial aboneleri 2x bonus alır!",
"title": "Oyun bitti!",
"winner": "Kazanan: {winner}",
"winners": "Kazananlar:",
"others": "Kalan oyuncular:",
"no_one": "    (yok)",
"duration": "Oyun süresi: {time}",
"night_caption":"<b>🌃 Gece\nSokağa sadece cesurlar çıktı. Sabah hayatta kalanları sayacağız..</b>",
"alive_players":"<b>Hayatta olan oyuncular:</b>",
"1_min_day_start":"\n<b>Şafağa 1 dakika kaldı!</b>",
"don_choose":"🤵🏻 Mafya kurbanını seçti...",
"don_not_choose":"🚷 🤵🏻 Don kimseyi öldürmemeyi seçti.",
"day_start": "<b>🏙 {day}. gün\nGüneş doğdu ama gece olanları sadece birkaç kişi biliyor...</b>",
"no_night_deaths":"🧐 İnanılmaz ama gece kimse ölmedi...",
"from_them":"\nOnlardan:\n\n",
"peace_roles":"<b>Siviller - {count}\n {roles}</b>\n\n",
"mafia_roles":"<b>Mafya - {count}\n {roles}</b>\n\n",
"debate_time":"\n\n<b>Gece olanları tartışma zamanı...</b>",
"start_voting":"<b>Suçluları bulma zamanı.\nOylama 45 saniye</b>",
"hang_prompt":"<b>Kimi asmak istiyorsunuz?</b>",
"vote_end":"<b>Oylama bitti.\nKaos çıktı... Herkes evine dağıldı...</b>",
"no_consenus":"<b>Kasaba anlaşamadı ({yes} 👍 | {no} 👎 )...\nKimse asılmadı...</b>",
"voted_user":"<b>Gerçekten <a href='tg://user?id={tg_id}'>{first_name}</a> asılsın mı?</b>",
"confirm_hang":"<b>Gerçekten <a href='tg://user?id={tg_id}'>{first_name}</a> asılsın mı?\n\nOylama bitti.</b>",
"hang_protect":"<b>Oylama sonucu:\n\n{yes} 👍 | {no} 👎\n\n<a href='tg://user?id={tg_id}'>{first_name}</a> asılma korumasına sahipti!</b>",
"hang_no_protect":"<b>Oylama sonucu:\n\n{yes} 👍 | {no} 👎\n\n<a href='tg://user?id={tg_id}'>{first_name}</a> asılacak!</b>",
"hanged":"<a href='tg://user?id={tg_id}'>{first_name}</a> {role_label} idi!!",
"game_not_active":"Üzgünüz, oyun zaten başladı.",
"already_in_game":"Sabırlı olun, zaten oyundasınız! Anladınız mı? Oyundasınız! :)",
"joined_game":"✅ Tebrikler! <b>{group_name}</b> grubunda oyuna katıldınız.",
"greating_message":"Merhaba! <code>{first_name}</code>\nBen resmi 🤵🏻 Mafia oyun botuyum.",
"use_game_command":"Oyunu başlatmak için /game komutunu kullanın.",
"user_profile":"👤 <code>{first_name}</code>\n\n💶 Para: {coin}\n💎 Elmas: {stones}\n\n🛡 Koruma: {protection}\n🎗️ Asılma koruması: {hang_protect}\n📂 Belgeler: {docs}\n🔰 Geroy koruması: {geroy_protect}\n\n🎯Kazanılan maçlar: {wins}\n🎲 Tüm maçlar: {all_played}\n\n🃏 Aktif roller:\n{text}",
"send_money":"{amount} 💵 gönderdi.",
"send_stone":"{amount} 💎 gönderdi.",
"left_game":"<a href='tg://user?id={telegram_id}'> {first_name}</a> bu şehrin kötülüklerine dayanamadı ve kendini astı. Rolü {role_label_text} idi.",
"59_left":"⏳ Kayıt için 59 saniye kaldı!",
"29_left":"⏳ Kayıt için 29 saniye kaldı!",
"not_enough_players":"Oyunu başlatmak için yeterli oyuncu yok...\n\nMinimum oyuncu sayısı - 4",
"game_started":"Oyun başladı!\nBirkaç saniye içinde bot rolünüzü ve açıklamasını özel mesajla gönderecek.",
"trial_expired":"❌ Grup aboneliği sona erdi.\nDevam etmek için yöneticiyle iletişime geçin.\n\nYönetici : @RedDon_Mafia",
"registration_started":"Kayıt başladı",
"registration_started_notify":"⏰ Hatırlatma!\n\n📢 Grupta yeni oyun için kayıt başladı.\n",
"registration_stopped":"🛑 Kayıt durduruldu.",
"registration_extended":"Kayıt süresi +30 saniye uzatıldı!\n",
"time_left":"Oyunun başlamasına {minutes} dakika {seconds} saniye kaldı",
"no_active_game":"❗ Bu sohbette aktif oyun yok.",
"game_stopped":"🛑 Oyun zorla durduruldu.",
"top_daily":"🏆 Grup içi günlük sıralama",
"top_weekly":"🏆 Grup içi haftalık sıralama",
"top_monthly":"🏆 Grup içi aylık sıralama",
"mafia_companions":"Takım arkadaşlarınızı unutmayın:",
"no":"Hayır",
"active_role_used":"🎭 Aktif rol kullanıldı",
"dance_party":"🥲 Sevgilinizle vakit geçirin",
"no_write_game_time":"🥲 Oyun sırasında yazamazsınız!\n🔈 45 saniyeliğine susturuldunuz.",
"last_wish_message":"{role_label_text} <a href='tg://user?id={tg_id}'>{first_name}</a> son sözleri:\n\n{text}",
"last_wish_send":"✅ Son sözleriniz gruba gönderildi.",
"buy_stone_group":"💎 Elmas satın al",
"buy_money_group":"💶 Para satın al",
"buy_stone_group_desc":"Satın almadan önce bakiyenizde yeterli stars olduğundan emin olun.",
"payment_method_choose":"Ödeme yöntemini seçin:",
"buy_role":"🎭 Rol satın almak için aşağıdan seçin:",
"not_enough_stones":"💎 Yeterli elmas yok!",
"not_enough_money":"💵 Yeterli para yok!",
"role_bought":"✅ Rol satın aldınız!",
"buy_another_role":"🎭 Başka rol almak ister misiniz?",
"roles_list":"🎎 Mevcut roller listesi\n\nAçıklama için role tıklayın",
"money_in_money":"💶 Parayı nakit olarak çekme\n\nFiyatlar:\n\n{money}\n\nÖdeme için @RedDon_Mafia ile iletişime geçin.",
"stone_in_money":"💎 Elmasları nakit olarak çekme\n\nFiyatlar:\n\n{stone}\n\nÖdeme için @RedDon_Mafia ile iletişime geçin.",
"money_in_stars":"💶 Stars karşılığında para al\nMiktar seçin:",
"stone_in_stars":"💎 Stars karşılığında elmas al\nMiktar seçin:",
"choose_quantity":"Miktar seçin:",
"action_choose":"seçtiniz.",
"no_go_doc":"🚷 👨🏼‍⚕️ Doktor hiçbir yere gitmemeyi seçti.",
"go_doc":"👨🏼‍⚕️ Doktor gece nöbetine gitti...",
"action_no_choose":"Kimseyi seçmediniz.",
"late":"Geç kaldınız.",
"daydi_no_go":"🚷 🧙🏼‍♂️ Serseri hiçbir yere gitmedi.",
"daydi_go":"🧙🏼‍♂️ Serseri birinin evine gitti...",
"com_no_go":"🚷 🕵️ Komiser dinlenmeyi seçti.",
"com_shoot":"🕵️ Komiser Katani silahını doldurdu...",
"com_check":"🕵️ Komiser Katani kötülüğü aramaya gitti...",
"lover_no_go":"🚷 💃🏼 Sevgili kimseyi beklemiyor.",
"lover_go":"💃🏼 Sevgili bir misafir bekliyor...",
"don_become":"🤵🏻 Don öldü, şimdi mafyalardan biri yeni Don oldu!",
"die":"⚰️ Ölüm",
"empty":"🥡 Boş kutu",
"prof_chosen":"🎩 Seçilen kutuda {reward} vardı!",
"hang_action":"Kimi asmak istiyorsunuz?",
"no_hang_choose":"kimse asılmasın dedi",
"hang_choose":"asılması için oy verdi",
"dead_cant_vote":"⚠️ Ölü oyuncular oy veremez!",
"no_player":"❌ Bu oyunda değilsiniz!",
"cant_vote_self":"❌ Kendinize oy veremezsiniz!",
"lover_waiting":"❌ Sevgiliniz sizi bekliyor, oy veremezsiniz!",
"vote_accepted":"👍 Oyunuz kabul edildi.",
"stone_ended":"❌ Elmas kalmadı!",
"stone_already_taken":"⚠️ Zaten aldınız!",
"stone_not_in_game":"❌ Oyunda değilsiniz.",
"user_not_found":"❌ Kullanıcı bulunamadı!",
"join_game": "🤵🏻 Katıl",
"view_role": "🎭 Rolü görüntüle",
"go_to_bot": "🤖 Bota git",
"vote": "🗳 Oy ver",
"already_in_another_game":"⚠️ Başka bir oyundasınız, önce ona katılmalısınız!",

}




qz_texts = {
    "ROLES_CHOICES": [
        ("peace", "👨🏼 Бейбіт тұрғын"),
        ("nogiron", "👨🏻‍🦼‍➡️ Мүгедек"),
        ("suid", "🤦🏻 Суицид"),
        ("doc", "👨🏼‍⚕️ Дәрігер"),
        ("daydi", "🧙🏼‍♂️ Кезбе"),
        ("com", "🕵🏻‍♂️ Комиссар катани"),
        ("kam", "💣 Камикадзе"),
        ("lover", "💃🏻 Ғашық"),
        ("mafia", "🤵🏼 Мафия"),
        ("don", "🤵🏻 Дон"),
        ("adv", "👨🏻‍💻 Адвокат"),
        ("back_main", "⬅️ Артқа"),
    ],

    "WINNER_LABEL": {
        "peace": "👨🏼 Бейбіт тұрғындар",
        "mafia": "🤵🏻 Мафиялар",
    },

    "DESCRIPTIONS": {
        "peace": "🧑🏻 Бейбіт тұрғын. Сіздің міндетіңіз — мафияны табу және күндізгі дауыс беруде оларды асып жіберуге көмектесу.",
        "nogiron": "👨🏻‍🦼‍➡️ Мүгедек. Сіз тек тұрғындар жағындасыз, дауыс беру кезінде мафияға дауыс беріп, асып жібересіз.",
        "don": "🤵🏻 Дон. Мафиялар басшысы. Әр түнде құрбан таңдайсыз және бүкіл мафия сіздің шешіміңізге бағынады.",
        "mafia": "🤵🏼 Мафия. Донмен бірге жұмыс істейсіз, түнде құрбан таңдайсыз. Дон өлсе, оның орнын баса аласыз.",
        "com": "🕵🏻 Комиссар. Әр түнде ойыншыны тексереді, күдікті болса ата алады. Бейбіт тұрғындардың қорғаушысы.",
         "doc": "🧑🏻‍⚕️ Дәрігер. Әр түнде бір ойыншыны өлімнен сақтап қала алады. Бейбіт тұрғындардың үміті.",
        "lover": "💃🏻 Ғашық. Таңдалған ойыншыны бір түнге бұғаттайды, ол ешқандай әрекет жасай алмайды.",
        "adv": "👨🏻‍💼 Адвокат. Мафия жағында. Таңдалған мафияны Комиссар көзіне бейбіт тұрғын етіп көрсетеді.",
        "suid": "🤦🏻 Суицид. Егер сізді күндіз асса, ойын нәтижесіне қарамастан, бірден жеңіске жетесіз.",
        "daydi": "🧙🏻 Кезбе. Түнде бір үйге барып, сол жерде болған оқиғалардың куәсі бола алады.",
         "kam": "💣 Камикадзе. Егер сізді асса, қалаған бір ойыншыны өзіңізбен бірге алып кете аласыз.",
    },
    "ACTIONS": {
    # Mafia
    "don_kill": "🤵🏻 Мафия келесі құрбан үшін дауыс беріп жатыр: ",
    "mafia_vote": "🤵🏻 Бүгін түнде кімді өлтіруге дауыс бересіз?",
    "adv_mask": "👨🏻‍💻 Қай мафия мүшесін жасырамыз?",
    # Peace
    "doc_heal": "👨🏼‍⚕️ Бүгін түнде кімді емдейміз?",
    "com_deside": " 🕵🏻‍♂️ Бүгін түнде не істегіңіз келеді?",
    "com_check": "🔍 Кімді тексереміз?",
    "com_shoot": "🔫 Кімді атамыз?",
    "daydi_watch": "🧙🏼‍♂️ Бүгін түнде кімнің үйіне бөтелке алу үшін барасыз?",
    "lover_block": "💃🏻 Бүгін түнді кіммен өткізгіңіз келеді?",

    "kamikaze_blow": "💣 Кімді жарып жібереміз?",
   
},

"punish_afk": "Түнде {role_label} <a href='tg://user?id={pid}'>{name}</a> қатыгездікпен өлтірілді...\nОл өлім алдында мынадай сөз қалдырды:\n'Мен ойын кезінде енді ешқашан ұйықтамаймын-а-а-а-а-а-ан!'",
"reg_started": "Тіркелу басталды",
"reg_list": "Тіркелгендер:",
"total": "Барлығы {count} адам",
"no_players": "Әлі ешкім тіркелмеді",
"bot_no_rights": "⚠️ Ботқа жеткілікті админ құқықтары берілмеген!\nСәлем! Мен Mafia ойынының ресми ботымын.\n\nКелесі рұқсаттар қажет:\n",
"bot_no_rights_add": "☑️ Админ ету\n☑️ Хабарламаларды өшіру\n☑️ Қатысушыларды шектеу\n☑️ Хабарламаларды бекіту\n",
"bot_no_rights_delete": "☑️ Хабарламаларды өшіру\n",
"bot_no_rights_restrict": "☑️ Қатысушыларды шектеу\n",
"bot_no_rights_pin": "☑️ Хабарламаларды бекіту\n",
"don_killed": "🤵🏻 Сіздің Дон қайтыс болды.\nЕнді сіз жаңа Дон болдыңыз!",
"don_become": "🤵🏻 Дон қаза тапты, енді мафиялардың бірі жаңа Дон болды!",
"don_notify": "🤵🏻 Сіздің жаңа Доныңыз: <a href='tg://user?id={new_don_id}'>{first_name}</a>",
"mafia_target": "Мафияның дауыс беруі аяқталды\nМафиялар {mafia_target} 💀 қатыгездікпен өлтірді.",
"u_killed": "<b>Сізді өлтірді :(</b>\nСіз мұнда өлім алдындағы хабар қалдыра аласыз",
"u_saved": "<b>Сізді {protector_role_label} құтқарды!</b>\nСіз тірі қалдыңыз!",
"someone_interested": "Біреу сіздің рөліңізге қызықты...",
"com_check_result": "<a href='tg://user?id={com_check_target}'>{target_name}</a> - {visible_role_text}","daydi_report": "🧙🏼‍♂️ Түнде сіз бөтелке үшін <a href='tg://user?id={daydi_house_id}'>{house_owner}</a> ге бардыңыз және ол жерде {visitors} көрдіңіз.",
"daydi_report_no_visitors": "🧙🏼‍♂️ Түнде сіз <a href='tg://user?id={daydi_house_id}'>{house_owner}</a> ден бөтелкелерді алып, қайтып кеттіңіз. Күдікті ештеңе болған жоқ.",
"lover_blocked": "'Сен менімен бәрін ұмыт...', - деп ән айтты 💃🏼 <b>Ғашық</b>",
"win_report": "🏆 Ойын аяқталды!\n{role_text} рөлінде жеңіске жеттіңіз!\n💵 Сыйлық: {reward}\n\n{user_link}\n\n💵 Ақша: {coins}\n💎 Тастар: {stones}\n🛡 Қорғаныс: {protection}\n📂 Құжаттар: {docs}\n\n@MafiaRedDonOfficial жазылушылары 2x бонус алады!",
"lose_report": "🎮 Ойын аяқталды!\nҚатысқаныңыз үшін сыйлық: {reward} 💵\n\n{user_link}\n\n💵 Ақша: {coins}\n💎 Тастар: {stones}\n🛡 Қорғаныс: {protection}\n📂 Құжаттар: {docs}\n\n@MafiaRedDonOfficial жазылушылары 2x бонус алады!",
"title": "Ойын аяқталды!",
"winner": "Жеңімпаз: {winner}",
"winners": "Жеңімпаздар:",
"others": "Қалған ойыншылар:",
"no_one": "    (жоқ)",
"duration": "Ойын: {time} уақытқа созылды",
"night_caption": "<b>🌃 Түн\nКөшеге тек батыл әрі қорықпайтын адамдар шықты. Таңертең тірі қалғандарды санаймыз..</b>",
"alive_players": "<b>Тірі ойыншылар:</b>",
"1_min_day_start": "\n<b>Таңға дейін 1 минут қалды!</b>",
"don_choose": "🤵🏻 Мафия келесі олжасын таңдады...",
"don_not_choose": "🚷 🤵🏻 Дон ешкімді өлтірмеуді жөн көрді.",
"day_start": "<b>🏙 {day}-күн\nКүн шықты, бірақ түн артында не болғанын тек бірнеше адам біледі...</b>",
"no_night_deaths": "🧐 Сену қиын, түнде ешкім өлмеді...",
"from_them": "\nОлардан:\n\n",
"peace_roles": "<b>Бейбіт тұрғындар - {count}\n {roles}</b>\n\n",
"mafia_roles": "<b>Мафиялар - {count}\n {roles}</b>\n\n",
"debate_time": "\n\n<b>Түнде болған оқиғаларды талқылайтын уақыт келді...</b>",
"start_voting": "<b>Кінәлілерді анықтап, жазалау уақыты келді.\nДауыс беруге 45 секунд</b>",
"hang_prompt": "<b>Кінәлілерді іздеу уақыты келді!\nКімді асқыңыз келеді?</b>",
"vote_end": "<b>Дауыс беру аяқталды.\nДауыс беру жанжалға айналып кетті... Барлығы үйлеріне тарады...</b>",
"no_consenus": "<b>Тұрғындар келісе алмады ({yes} 👍 | {no} 👎 )...\nКелісе алмағандықтан ешкім асылмады...</b>",
"voted_user": "<b>Шынымен <a href='tg://user?id={tg_id}'>{first_name}</a> ні асқыңыз келе ме?</b>",
"confirm_hang": "<b>Шынымен <a href='tg://user?id={tg_id}'>{first_name}</a> ні асқыңыз келе ме?\n\nДауыс беру аяқталды.</b>",
"hang_protect": "<b>Дауыс беру нәтижелері:\n\n{yes} 👍  |  {no} 👎\n\n<a href='tg://user?id={tg_id}'>{first_name}</a> - ні асудан қорғанысы бар және ол асылмады! :)</b>",
"hang_no_protect": "<b>Дауыс беру нәтижелері:\n\n{yes} 👍  |  {no} 👎\n\n<a href='tg://user?id={tg_id}'>{first_name}</a> - ні асамыз! :)</b>",
"hanged": "<a href='tg://user?id={tg_id}'>{first_name}</a> - {role_label} еді!!",
"game_not_active": "Кешіріңіз, ойын әлдеқашан басталған.",
"already_in_game": "Сабыр етіңіз, сіз ойындасыз! Түсіндіңіз бе? Ойында! :)",
"joined_game": "✅ Құттықтаймыз! Сіз <b>{group_name}</b> тобында ойынға қосылдыңыз.",
"greating_message": "Сәлем! <code>{first_name}</code>\nМен 🤵🏻Mafia ойынының ресми ботымын.",
"use_game_command": "Ойынды бастау үшін /game командасын пайдаланыңыз.",
"user_profile": "👤 <code>{first_name}</code>\n\n💶 Ақша: {coin}\n💎 Алмастар: {stones}\n\n🛡 Қорғаныс: {protection}\n🎗️ Асылудан қорғаныс: {hang_protect}\n📂 Құжаттар: {docs}\n🔰 Герой қорғанысы: {geroy_protect}\n\n🎯Жеңіс: {wins}\n🎲 Барлық ойындар: {all_played}\n\n🃏 Белсенді рөлдер:\n{text}",
"send_money": "ға {amount} 💵 жіберді.",
"send_stone": "ға {amount} 💎 жіберді.",
"left_game": "<a href='tg://user?id={telegram_id}'>{first_name}</a> Бұл қаланың зұлымдықтарына шыдай алмай, өзін асып қойды. Ол {role_label_text} еді.",
"59_left": "⏳ Тіркелуге 59 секунд қалды!",
"29_left": "⏳ Тіркелуге 29 секунд қалды!",
"not_enough_players": "Ойынды бастау үшін ойыншылар жеткіліксіз...\n\nМинималды ойыншылар саны - 4",
"game_started": "Ойын басталды!\nБірнеше секунд ішінде бот сізге рөл және оның сипаттамасын жеке хабарлама арқылы жібереді.",
"trial_expired": "❌ Топтың жазылым мерзімі аяқталды.\nЖалғастыру үшін админмен байланысыңыз.\n\nAdmin : @RedDon_Mafia",
"registration_started": "Тіркелу басталды",
"registration_started_notify": "⏰ Еске салу!\n\n📢 Топта жаңа ойынға тіркелу басталды.\n",
"registration_stopped": "🛑 Тіркелу тоқтатылды.",
"registration_extended": "Ойынға тіркелу уақыты +30 секундқа ұзартылды!\n",
"time_left": "Ойын басталуына {minutes} минут {seconds} секунд қалды",
"no_active_game": "❗ Қазір бұл чатта белсенді ойын жоқ.",
"game_stopped": "🛑 Ойын мәжбүрлі түрде тоқтатылды.",
"top_daily": "🏆 Топтағы топ рейтинг (күндік)",
"top_weekly": "🏆 Топтағы топ рейтинг (апталық)",
"top_monthly": "🏆 Топтағы топ рейтинг (айлық)",
"mafia_companions": "Серіктеріңізді есте сақтаңыз:",
"no": "Жоқ",
"active_role_used": "🎭 Белсенді рөл қолданылды",
"dance_party": "🥲 Сіз Ғашықпен уақытты көңілді өткізесіз",
"no_write_game_time": "🥲 Ойын уақытында жазуға рұқсат жоқ!\n🔈 45 секундқа mute берілді.",
"last_wish_message": "{role_label_text} <a href='tg://user?id={tg_id}'>{first_name}</a> соңғы сөздері:\n\n{text}",
"last_wish_send": "✅ Сіздің соңғы сөздеріңіз топқа жіберілді.",
"buy_stone_group": "💎 Алмас сатып алу",
"buy_money_group": "💶 Ақша сатып алу",
"buy_stone_group_desc": "Сатып алмас бұрын шотыңызда жеткілікті stars бар екенін тексеріңіз.",
"payment_method_choose": "Қажетті төлем жүйесін таңдаңыз:",
"buy_role": "🎭 Рөл сатып алу үшін төмендегі рөлдердің бірін таңдаңыз:",
"not_enough_stones": "💎 Алмас жеткіліксіз!",
"not_enough_money": "💵 Шотыңызда жеткілікті ақша жоқ!",
"role_bought": "✅ Сіз рөл сатып алдыңыз!",
"buy_another_role": "🎭 Тағы рөл сатып аласыз ба?",
"roles_list": "🎎 Қолжетімді рөлдер тізімі\n\nСипаттамасын көру үшін рөл атауын басыңыз",
"money_in_money": "💶 Ақшаны қолма-қол алу\n\nБағалар:\n\n{money}\n\nТөлем жасау үшін @RedDon_Mafia ға жазыңыз.",
"stone_in_money": "💎 Алмасты қолма-қол алу\n\nБағалар:\n\n{stone}\n\nТөлем жасау үшін @RedDon_Mafia ға жазыңыз.",
"money_in_stars": "💶 Ақшаны жұлдыздар арқылы алу\nҚажетті мөлшерді таңдаңыз:",
"stone_in_stars": "💎 Алмасты жұлдыздар арқылы алу\nҚажетті мөлшерді таңдаңыз:",
"choose_quantity": "Қажетті мөлшерді таңдаңыз:",
"action_choose": " таңдадыңыз.",
"no_go_doc": "🚷 👨🏼‍⚕️ Дәрігер ешқайда бармауды жөн көрді.",
"go_doc": "👨🏼‍⚕️ Дәрігер түнгі кезекшілікке кетті...",
"action_no_choose": "Сіз ешкімді таңдамадыңыз.",
"late": "Сіз кешіктіңіз.",
"daydi_no_go": "🚷 🧙🏼‍♂️ Кезбе ешқайда бармауды жөн көрді.",
"daydi_go": "🧙🏼‍♂️ Кезбе біреуге бөтелке алу үшін кетті...",
"com_no_go": "🚷 🕵️‍ Комиссар бүгін демалуды қалады.",
"com_shoot": "🕵️‍ Комиссар Катани тапаншасын оқтады...",
"com_check": "🕵️‍ Комиссар Катани зұлымдарды іздеуге кетті...",
"lover_no_go": "🚷 💃🏼 Ғашық ешкімді күтпейді.",
"lover_go": "💃🏼 Ғашық бір қонақты күтіп отыр...",
"adv_no_go": "🚷 👨🏻‍💻 Адвокат ешкімді қорғамауды жөн көрді.",
"adv_go": "👨🏻‍💻 Адвокат өз клиентін қорғауға кетті...",
"hang_action": "Кінәлілерді іздеу уақыты келді!\nКімді асқыңыз келеді?",
"no_hang_choose": "ешкімді аспауға ұсыныс жасады",
"hang_choose": "ға дауыс берді",
"dead_cant_vote": "⚠️ Өлі ойыншылар дауыс бере алмайды!",
"no_player": "❌ Сіз бұл ойында қатысып жатқан жоқсыз!",
"cant_vote_self": "❌ Өзіңізге дауыс бере алмайсыз!",
"lover_waiting": "❌ Сізді ғашығыңыз күтіп тұр, дауыс бере алмайсыз!",
"vote_accepted": "👍 Дауысыңыз қабылданды.",
"stone_ended": "❌ Алмас таусылды!",
"stone_already_taken": "⚠️ Сіз әлдеқашан алғансыз!",
"stone_not_in_game": "❌ Сіз ойында жоқсыз. Тек ойындағылар алады!",
"user_not_found": "❌ Пайдаланушы табылмады!",
"join_game": "🤵🏻 Қосылу",
"view_role": "🎭 Рөлді көру",
"go_to_bot": "🤖 Ботқа өту",
"vote": "🗳 Дауыс беру",
"already_in_another_game": "❌ Сіз қазірдің өзінде басқа ойында қатысып жатырсыз!",
}


LANGUAGE_CHOICES = [
        ('uz', 'Uzbek'),
        ('ru', 'Russian'),
        ('en', 'English'),
        ('tr', 'Turkish'),
        ("qz", "Kazakh"),
    ]



ROLES_BY_COUNT = {
    4:  ["nogiron", "peace", "don", "doc"],
    5:  ["nogiron", "peace", "don", "doc", "peace"],
    6:  ["nogiron", "don", "doc", "com", "peace", "mafia"],
    7:  ["nogiron", "don", "doc", "com", "peace", "mafia", "peace"],
    8:  ["nogiron", "don", "doc", "com", "peace", "mafia", "daydi", "peace"],
    9:  ["nogiron", "don", "doc", "com", "peace", "mafia", "daydi", "peace", "peace"],
    10: ["nogiron", "don", "doc", "com", "peace", "mafia", "daydi", "mafia", "peace", "mafia"],
    11: ["nogiron", "don", "doc", "com", "peace", "mafia", "daydi", "mafia", "peace", "mafia", "peace"],
    12: ["nogiron", "don", "doc", "com", "peace", "mafia", "daydi", "mafia",  "mafia", "lover", "peace"],

    13: ["nogiron", "don", "doc", "com", "peace", "mafia", "daydi", "mafia",  "mafia", "lover",  "peace"],
    14: ["nogiron", "don", "doc", "com", "peace", "mafia", "daydi", "mafia",  "mafia", "lover",   "peace"],
    15: ["nogiron", "don", "doc", "com", "peace", "mafia", "daydi", "mafia",  "mafia", "lover",    "peace"],

   
}




MONEY_FOR_STAR ={
    "1000": 7,
    "10000": 77,
    "50000": 340,
    "100000": 680,
}

STONE_FOR_STAR = {
    "1": 7,
    "10": 68,
    "30": 185,
    "50": 237,
    "70": 382,
    "100": 513,
}

ROLE_EMOJIS = {
    "peace": "👨🏼",
    'nogiron': "👨🏻‍🦼‍➡️",
    "doc": "👨🏼‍⚕️",
    "daydi": "🧙🏼‍♂️",
    "com": "🕵🏻‍♂️",
    "kam": "💣",
    "lover": "💃🏻",
    
    "suid": "🤦🏻",


    "mafia": "🤵🏼",
    "don": "🤵🏻",
    "adv": "👨🏻‍💻",
    
    "back_main": "⬅️",
}

ROLE_PRICES_IN_STONES = {
   
    "com":3,
    "don":3,
    
    "kam": 2,
    
    "mafia":1,
    }
ROLE_PRICES_IN_MONEY = {
    "lover": 400,
    "daydi": 400,
    "adv": 400,
    "suid": 300,
    
    "nogiron": 300,
    "doc": 350,
    "peace": 200,
}
    